exports.seed = knex => knex('exercises').del()
  .then(() => knex('exercises').insert([
    { id: 1, name: 'Bear Crawl Fire Feet', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 2, name: 'Bicycling', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 1 },
    { id: 3, name: 'Bicycling, Stationary', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 4, name: 'Burpee', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 5, name: 'Butt Kicks', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 6, name: 'Defensive Slide', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 7, name: 'Double Under', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 1 },
    { id: 8, name: 'Elliptical Trainer', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 9, name: 'Fast Kick With Arm Circles', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 10, name: 'Football Up-Down', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 11, name: 'High Knee Jog', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 12, name: 'Jog In Place', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 13, name: 'Jogging-Treadmill', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 14, name: 'Jumping Jack', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 15, name: 'Lateral Speed Step', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 16, name: 'Prowler Sprint', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 1 },
    { id: 17, name: 'Punches', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 18, name: 'Recumbent Bike', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 19, name: 'Rope Jumping', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 1 },
    { id: 20, name: 'Rowing, Stationary', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 21, name: 'Running, Treadmill', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 22, name: 'Skating', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 1 },
    { id: 23, name: 'Slow Jog', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 24, name: 'Stairmaster', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 25, name: 'Step Mill', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 26, name: 'Trail Running/Walking', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 1 },
    { id: 27, name: 'Vertical Mountain Climber', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 28, name: 'Walking High Knees', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 1 },
    { id: 29, name: 'Walking, Treadmill', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 1 },
    { id: 30, name: 'Clean', muscle_id: 17, exercise_type_id: 2 },
    { id: 31, name: 'Clean and Jerk', muscle_id: 12, exercise_type_id: 2 },
    { id: 32, name: 'Clean Deadlift', muscle_id: 17, exercise_type_id: 2 },
    { id: 33, name: 'Clean from Blocks', muscle_id: 10, exercise_type_id: 2 },
    { id: 34, name: 'Clean Pull', muscle_id: 10, exercise_type_id: 2 },
    { id: 35, name: 'Clean Shrug', muscle_id: 14, exercise_type_id: 2 },
    { id: 36, name: 'Frankenstein Squat', muscle_id: 10, exercise_type_id: 2 },
    { id: 37, name: 'Hang Clean', muscle_id: 10, exercise_type_id: 2 },
    { id: 38, name: 'Hang Clean - Below the Knees', muscle_id: 10, exercise_type_id: 2 },
    { id: 39, name: 'Hang Snatch', muscle_id: 17, exercise_type_id: 2 },
    { id: 40, name: 'Hang Snatch - Below Knees', muscle_id: 17, exercise_type_id: 2 },
    { id: 41, name: 'Heaving Snatch Balance', muscle_id: 10, exercise_type_id: 2 },
    { id: 42, name: 'Jerk Balance', muscle_id: 12, exercise_type_id: 2 },
    { id: 43, name: 'Jerk Dip Squat', muscle_id: 10, exercise_type_id: 2 },
    { id: 44, name: 'Kneeling Jump Squat', muscle_id: 15, exercise_type_id: 2 },
    { id: 45, name: 'Muscle Snatch', muscle_id: 17, exercise_type_id: 2 },
    { id: 46, name: 'Olympic Squat', muscle_id: 10, exercise_type_id: 2 },
    { id: 47, name: 'Overhead Squat', muscle_id: 10, exercise_type_id: 2 },
    { id: 48, name: 'Power Clean from Blocks', muscle_id: 17, exercise_type_id: 2 },
    { id: 49, name: 'Power Jerk', muscle_id: 10, exercise_type_id: 2 },
    { id: 50, name: 'Power Snatch', muscle_id: 17, exercise_type_id: 2 },
    { id: 51, name: 'Power Snatch from Blocks', muscle_id: 10, exercise_type_id: 2 },
    { id: 52, name: 'Push Press', muscle_id: 12, exercise_type_id: 2 },
    { id: 53, name: 'Push Press - Behind the Neck', muscle_id: 12, exercise_type_id: 2 },
    { id: 54, name: 'Rack Delivery', muscle_id: 12, exercise_type_id: 2 },
    { id: 55, name: 'Romanian Deadlift from Deficit', muscle_id: 17, exercise_type_id: 2 },
    { id: 56, name: 'Snatch', muscle_id: 10, exercise_type_id: 2 },
    { id: 57, name: 'Snatch Balance', muscle_id: 10, exercise_type_id: 2 },
    { id: 58, name: 'Snatch Deadlift', muscle_id: 17, exercise_type_id: 2 },
    { id: 59, name: 'Snatch from Blocks', muscle_id: 10, exercise_type_id: 2 },
    { id: 60, name: 'Snatch Shrug', muscle_id: 14, exercise_type_id: 2 },
    { id: 61, name: 'Split Clean', muscle_id: 10, exercise_type_id: 2 },
    { id: 62, name: 'Split Jerk', muscle_id: 10, exercise_type_id: 2 },
    { id: 63, name: 'Split Snatch', muscle_id: 17, exercise_type_id: 2 },
    { id: 64, name: 'Tall Muscle Snatch', muscle_id: 12, exercise_type_id: 2 },
    { id: 65, name: 'Wide Stance Stiff Legs', muscle_id: 17, exercise_type_id: 2 },
    { id: 66, name: '90-Degree Jump Squat Twist', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 67, name: 'Alien Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 68, name: 'Alternate Leg Diagonal Bound', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 69, name: 'Backward Medicine Ball Throw', muscle_id: 12, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 70, name: 'Bar Push-Up Smith Machine', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 71, name: 'Bench Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 72, name: 'Bench Sprint', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 73, name: 'Box Jump (Multiple Response)', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 74, name: 'Box Skip', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 75, name: 'Burpee Box Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 76, name: 'Burpee Over Barbell', muscle_id: 10, exercise_type_id: 3 },
    { id: 77, name: 'Burpee Pull-Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 78, name: 'Burpee Tuck Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 79, name: 'Burppe Box Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 80, name: 'Carioca Quick Step', muscle_id: 5, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 81, name: 'Catch and Overhead Throw', muscle_id: 2, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 82, name: 'Chest Push (multiple response)', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 83, name: 'Chest Push (single response)', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 84, name: 'Chest Push from 3 point stance', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 85, name: 'Chest Push with Run Release', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 86, name: 'Clapping Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 87, name: 'Decline Explosive Push-Up', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 88, name: 'Depth Jump Leap', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 89, name: 'Double Leg Butt Kick', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 90, name: 'Drop Push', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 91, name: 'Dumbbell Jump Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 3 },
    { id: 92, name: 'Dumbbell Seated Box Jump', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 3 },
    { id: 93, name: 'Fast Skipping', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 94, name: 'Feet Jack', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 95, name: 'Front Box Jump', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 96, name: 'Front Cone Hops (or hurdle hops)', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 97, name: 'Gorilla Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 98, name: 'Heavy Bag Thrust', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 99, name: 'Hurdle Hops', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 100, name: 'Ice Skater', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 101, name: 'Incline Push-Up Depth Jump', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 102, name: 'Isometric Chest Squeezes', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 103, name: 'Jump Lunge To Feet Jack', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 104, name: 'Jump Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 105, name: 'Jumping Jacks', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 106, name: 'Jumping Knee Up Down', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 107, name: 'Kettlebell Fire Feet', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 3 },
    { id: 108, name: 'Knee Tuck Jump', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 109, name: 'Kneeling Arm Drill', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 110, name: 'Lateral Bound', muscle_id: 5, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 111, name: 'Lateral Box Jump', muscle_id: 5, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 112, name: 'Lateral Cone Hops', muscle_id: 5, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 113, name: 'Lateral Hop 4 Times To Sprint', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 3 },
    { id: 114, name: 'Lateral Hop Holding Dumbbells', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 3 },
    { id: 115, name: 'Linear 3-Part Start Technique', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 116, name: 'Linear Acceleration Wall Drill', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 117, name: 'Linear Depth Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 118, name: 'Lunge Heel Kick', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 119, name: 'Medicine Ball Chest Pass', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 120, name: 'Medicine Ball Full Twist', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 121, name: 'Medicine Ball Ninja', muscle_id: 10, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 122, name: 'Medicine Ball Scoop Throw', muscle_id: 12, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 123, name: 'Mountain Climbers', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 124, name: 'Moving Claw Series', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 125, name: 'Overhead Slam', muscle_id: 2, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 126, name: 'Plyo Push-up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 127, name: 'Pop Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 128, name: 'Quick Leap', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 129, name: 'Return Push from Stance', muscle_id: 12, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 130, name: 'Reverse Burpee', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 131, name: 'Rocket Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 132, name: 'Running Lunge', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 133, name: 'Scissors Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 134, name: 'Side Hop-Sprint', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 135, name: 'Side Standing Long Jump', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 3 },
    { id: 136, name: 'Side to Side Box Shuffle', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 137, name: 'Single Leg Butt Kick', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 138, name: 'Single Leg Push-off', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 139, name: 'Single-Cone Sprint Drill', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 140, name: 'Single-Leg Box Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 141, name: 'Single-Leg Hop Progression', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 142, name: 'Single-Leg Lateral Hop', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 143, name: 'Single-Leg Stride Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 144, name: 'Sledgehammer Swings', muscle_id: 1, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 145, name: 'Slide Jump Shot', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 146, name: 'Southpaw Sprawl', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 147, name: 'Split Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 148, name: 'Sprawl Frog Kick', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 149, name: 'Square Hop', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 150, name: 'Standing Long Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 151, name: 'Standing Two-Arm Overhead Throw', muscle_id: 12, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 152, name: 'Star Jump', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 153, name: 'Stride Jump Crossover', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 154, name: 'Superman Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 155, name: 'Supine Chest Throw', equipment_type_id: 8, exercise_type_id: 3 },
    { id: 156, name: 'Supine One-Arm Overhead Throw', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 157, name: 'Supine Two-Arm Overhead Throw', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 158, name: 'Trap Bar Jump', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 3 },
    { id: 159, name: 'Triple Clap Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 160, name: 'Vertical Swing', muscle_id: 17, equipment_type_id: 9, exercise_type_id: 3 },
    { id: 161, name: 'Wall Ball Squat', muscle_id: 10, equipment_type_id: 8, exercise_type_id: 3 },
    { id: 162, name: 'Wall Mountain Climber', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 163, name: 'Wall Sprawl', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 164, name: 'Wide-Stance Jump Squat To Close-Stance', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 3 },
    { id: 165, name: 'Band Good Morning', muscle_id: 17, equipment_type_id: 1, exercise_type_id: 4 },
    { id: 166, name: 'Band Good Morning (Pull Through)', muscle_id: 17, equipment_type_id: 1, exercise_type_id: 4 },
    { id: 167, name: 'Barbell Glute Bridge', muscle_id: 15, exercise_type_id: 4 },
    { id: 168, name: 'Barbell Hip Thrust', muscle_id: 15, exercise_type_id: 4 },
    { id: 169, name: 'Bench Press - Powerlifting', exercise_type_id: 4 },
    { id: 170, name: 'Bench Press with Chains', exercise_type_id: 4 },
    { id: 171, name: 'Bench Press With Short Bands', muscle_id: 11, equipment_type_id: 1, exercise_type_id: 4 },
    { id: 172, name: 'Board Press', exercise_type_id: 4 },
    { id: 173, name: 'Box Squat', muscle_id: 10, exercise_type_id: 4 },
    { id: 174, name: 'Box Squat with Bands', muscle_id: 10, exercise_type_id: 4 },
    { id: 175, name: 'Chain Handle Extension', equipment_type_id: 12, exercise_type_id: 4 },
    { id: 176, name: 'Chain Press', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 4 },
    { id: 177, name: 'Deadlift with Bands', muscle_id: 4, exercise_type_id: 4 },
    { id: 178, name: 'Deadlift with Chains', muscle_id: 4, exercise_type_id: 4 },
    { id: 179, name: 'Deficit Deadlift', muscle_id: 4, exercise_type_id: 4 },
    { id: 180, name: 'Dumbbell Floor Press', equipment_type_id: 9, exercise_type_id: 4 },
    { id: 181, name: 'Floor Press', exercise_type_id: 4 },
    { id: 182, name: 'Floor Press with Chains', exercise_type_id: 4 },
    { id: 183, name: 'Glute Ham Raise', muscle_id: 17, equipment_type_id: 6, exercise_type_id: 4 },
    { id: 184, name: 'Good Morning', muscle_id: 17, exercise_type_id: 4 },
    { id: 185, name: 'Good Morning off Pins', muscle_id: 17, exercise_type_id: 4 },
    { id: 186, name: 'Hanging Bar Good Morning', muscle_id: 17, exercise_type_id: 4 },
    { id: 187, name: 'Hip Lift with Band', muscle_id: 15, equipment_type_id: 1, exercise_type_id: 4 },
    { id: 188, name: 'Kneeling Squat', muscle_id: 15, exercise_type_id: 4 },
    { id: 189, name: 'Pin Presses', exercise_type_id: 4 },
    { id: 190, name: 'Rack Pull with Bands', muscle_id: 4, exercise_type_id: 4 },
    { id: 191, name: 'Rack Pulls', muscle_id: 4, exercise_type_id: 4 },
    { id: 192, name: 'Reverse Band Bench Press', exercise_type_id: 4 },
    { id: 193, name: 'Reverse Band Box Squat', muscle_id: 10, exercise_type_id: 4 },
    { id: 194, name: 'Reverse Band Deadlift', muscle_id: 4, exercise_type_id: 4 },
    { id: 195, name: 'Reverse Band Power Squat', muscle_id: 10, exercise_type_id: 4 },
    { id: 196, name: 'Reverse Band Sumo Deadlift', muscle_id: 17, exercise_type_id: 4 },
    { id: 197, name: 'Seated Good Mornings', muscle_id: 4, exercise_type_id: 4 },
    { id: 198, name: 'Speed Box Squat', muscle_id: 10, exercise_type_id: 4 },
    { id: 199, name: 'Squat with Bands', muscle_id: 10, exercise_type_id: 4 },
    { id: 200, name: 'Squat with Chains', muscle_id: 10, exercise_type_id: 4 },
    { id: 201, name: 'Sumo Deadlift', muscle_id: 17, exercise_type_id: 4 },
    { id: 202, name: 'Sumo Deadlift with Bands', muscle_id: 17, exercise_type_id: 4 },
    { id: 203, name: 'Sumo Deadlift with Chains', muscle_id: 17, exercise_type_id: 4 },
    { id: 204, name: '3/4 Sit-Up', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 205, name: 'Ab Crunch Machine', muscle_id: 1, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 206, name: 'Ab Roller', muscle_id: 1, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 207, name: 'Advanced Kettlebell Windmill', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 208, name: 'Air Bike', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 209, name: 'Alternate Hammer Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 210, name: 'Alternate Heel Touchers', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 211, name: 'Alternate Incline Dumbbell Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 212, name: 'Alternating Cable Shoulder Press', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 213, name: 'Alternating Deltoid Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 214, name: 'Alternating Floor Press', muscle_id: 11, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 215, name: 'Alternating Hang Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 216, name: 'Alternating Kettlebell Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 217, name: 'Alternating Kettlebell Row', muscle_id: 6, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 218, name: 'Alternating Renegade Row', muscle_id: 6, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 219, name: 'Anti-Gravity Press', muscle_id: 12, exercise_type_id: 5 },
    { id: 220, name: 'Arnold Dumbbell Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 221, name: 'Around The World Pull-Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 222, name: 'Around The Worlds', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 223, name: 'Assisted Chin-Up', muscle_id: 2, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 224, name: 'Back Flyes - With Bands', muscle_id: 12, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 225, name: 'Balance Board', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 226, name: 'Ball Leg Curl', muscle_id: 17, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 227, name: 'Band Assisted Pull-Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 228, name: 'Band Hip Adductions', muscle_id: 5, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 229, name: 'Band Pull Apart', muscle_id: 12, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 230, name: 'Band Skull Crusher', equipment_type_id: 1, exercise_type_id: 5 },
    { id: 231, name: 'Bar Throw And Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 232, name: 'Barbell Ab Rollout', muscle_id: 1, exercise_type_id: 5 },
    { id: 233, name: 'Barbell Ab Rollout - On Knees', muscle_id: 1, exercise_type_id: 5 },
    { id: 234, name: 'Barbell Bench Press - Medium Grip', muscle_id: 11, exercise_type_id: 5 },
    { id: 235, name: 'Barbell Bench Press-Wide Grip', muscle_id: 11, exercise_type_id: 5 },
    { id: 236, name: 'Barbell Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 237, name: 'Barbell Curls Lying Against An Incline', muscle_id: 7, exercise_type_id: 5 },
    { id: 238, name: 'Barbell Deadlift', muscle_id: 17, exercise_type_id: 5 },
    { id: 239, name: 'Barbell Deadlift Bent Row Complex', muscle_id: 6, exercise_type_id: 5 },
    { id: 240, name: 'Barbell Front Raise', muscle_id: 12, exercise_type_id: 5 },
    { id: 241, name: 'Barbell Front-To-Back Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 242, name: 'Barbell Full Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 243, name: 'Barbell Guillotine Bench Press', muscle_id: 11, exercise_type_id: 5 },
    { id: 244, name: 'Barbell Hack Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 245, name: 'Barbell Incline Bench Press Medium-Grip', muscle_id: 11, exercise_type_id: 5 },
    { id: 246, name: 'Barbell Incline Shoulder Raise', muscle_id: 12, exercise_type_id: 5 },
    { id: 247, name: 'Barbell Lunge', muscle_id: 10, exercise_type_id: 5 },
    { id: 248, name: 'Barbell Rear Delt Row', muscle_id: 12, exercise_type_id: 5 },
    { id: 249, name: 'Barbell Reverse Lunge', muscle_id: 10, exercise_type_id: 5 },
    { id: 250, name: 'Barbell Rollout from Bench', muscle_id: 1, exercise_type_id: 5 },
    { id: 251, name: 'Barbell Seated Calf Raise', muscle_id: 9, exercise_type_id: 5 },
    { id: 252, name: 'Barbell Shoulder Press', muscle_id: 12, exercise_type_id: 5 },
    { id: 253, name: 'Barbell Shrug', muscle_id: 14, exercise_type_id: 5 },
    { id: 254, name: 'Barbell Shrug Behind The Back', muscle_id: 14, exercise_type_id: 5 },
    { id: 255, name: 'Barbell Side Bend', muscle_id: 1, exercise_type_id: 5 },
    { id: 256, name: 'Barbell Side Split Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 257, name: 'Barbell Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 258, name: 'Barbell Squat To A Bench', muscle_id: 10, exercise_type_id: 5 },
    { id: 259, name: 'Barbell Squat To A Box', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 260, name: 'Barbell Step Ups', muscle_id: 10, exercise_type_id: 5 },
    { id: 261, name: 'Barbell Thruster', muscle_id: 10, exercise_type_id: 5 },
    { id: 262, name: 'Barbell Walking Lunge', muscle_id: 10, exercise_type_id: 5 },
    { id: 263, name: 'Battling Ropes', muscle_id: 12, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 264, name: 'Bear Crawl Shoulder Tap', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 265, name: 'Bench Dips', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 266, name: 'Bench Press - With Bands', muscle_id: 11, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 267, name: 'Bent Over Barbell Row', muscle_id: 6, exercise_type_id: 5 },
    { id: 268, name: 'Bent Over Dumbbell Rear Delt Raise With Head On Bench', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 269, name: 'Bent Over Low-Pulley Side Lateral', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 270, name: 'Bent Over One-Arm Long Bar Row', muscle_id: 6, exercise_type_id: 5 },
    { id: 271, name: 'Bent Over Two-Arm Long Bar Row', muscle_id: 6, exercise_type_id: 5 },
    { id: 272, name: 'Bent Over Two-Dumbbell Row', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 273, name: 'Bent Over Two-Dumbbell Row With Palms In', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 274, name: 'Bent Press', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 275, name: 'Bent-Arm Barbell Pullover', muscle_id: 2, exercise_type_id: 5 },
    { id: 276, name: 'Bent-Arm Dumbbell Pullover', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 277, name: 'Bent-Knee Hip Raise', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 278, name: 'Biceps Curl To Shoulder Press', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 279, name: 'Body Tricep Press', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 280, name: 'Body Triceps Press Using Flat Bench', equipment_type_id: 12, exercise_type_id: 5 },
    { id: 281, name: 'Body-Up', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 282, name: 'Bodyweight Flyes', muscle_id: 11, exercise_type_id: 5 },
    { id: 283, name: 'Bodyweight Lunge', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 284, name: 'Bodyweight Mid Row', muscle_id: 6, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 285, name: 'Bodyweight Reverse Lunge', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 286, name: 'Bodyweight Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 287, name: 'Bodyweight Walking Lunge', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 5 },
    { id: 288, name: 'Bosu Ball Cable Crunch With Side Bends', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 289, name: 'Bosu Ball Crunch', muscle_id: 1, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 290, name: 'Bosu Ball Push-Up', muscle_id: 11, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 291, name: 'Bosu Ball Squat', muscle_id: 10, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 292, name: 'Bottoms Up', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 293, name: 'Bottoms-Up Clean From The Hang Position', muscle_id: 13, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 294, name: 'Box Squat with Chains', muscle_id: 10, exercise_type_id: 5 },
    { id: 295, name: 'Bradford/Rocky Presses', muscle_id: 12, exercise_type_id: 5 },
    { id: 296, name: 'Breakdancer', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 297, name: 'Burpee To Medicine Ball Press', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 5 },
    { id: 298, name: 'Butt Lift (Bridge)', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 299, name: 'Butt-Ups', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 300, name: 'Butterfly', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 301, name: 'Cable Chest Press', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 302, name: 'Cable Crossover', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 303, name: 'Cable Crunch', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 304, name: 'Cable Deadlifts', muscle_id: 10, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 305, name: 'Cable Hammer Curls - Rope Attachment', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 306, name: 'Cable Hip Adduction', muscle_id: 10, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 307, name: 'Cable Incline Pushdown', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 308, name: 'Cable Incline Triceps Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 309, name: 'Cable Internal Rotation', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 310, name: 'Cable Iron Cross', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 311, name: 'Cable Judo Flip', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 312, name: 'Cable Lying Triceps Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 313, name: 'Cable One Arm Tricep Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 314, name: 'Cable Preacher Curl', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 315, name: 'Cable Rear Delt Fly', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 316, name: 'Cable Reverse Crunch', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 317, name: 'Cable Rope Overhead Triceps Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 318, name: 'Cable Rope Rear-Delt Rows', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 319, name: 'Cable Russian Twists', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 320, name: 'Cable Seated Crunch', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 321, name: 'Cable Seated Lateral Raise', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 322, name: 'Cable Shoulder Press', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 323, name: 'Cable Shrugs', muscle_id: 14, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 324, name: 'Cable Wrist Curl', muscle_id: 13, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 325, name: 'Calf Press', muscle_id: 9, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 326, name: 'Calf Press On The Leg Press Machine', muscle_id: 9, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 327, name: 'Calf Raise On A Dumbbell', muscle_id: 9, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 328, name: 'Calf Raises - With Bands', muscle_id: 9, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 329, name: 'Calf-Machine Shoulder Shrug', muscle_id: 14, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 330, name: 'Car Drivers', muscle_id: 12, exercise_type_id: 5 },
    { id: 331, name: 'Chair Squat', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 332, name: 'Chin-Up', muscle_id: 2, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 333, name: 'Clam', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 334, name: 'Clean and Press', muscle_id: 12, exercise_type_id: 5 },
    { id: 335, name: 'Clock Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 336, name: 'Close-Grip Barbell Bench Press', exercise_type_id: 5 },
    { id: 337, name: 'Close-Grip Dumbbell Press', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 338, name: 'Close-Grip EZ Bar Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 339, name: 'Close-Grip EZ-Bar Curl with Band', muscle_id: 7, exercise_type_id: 5 },
    { id: 340, name: 'Close-Grip EZ-Bar Press', exercise_type_id: 5 },
    { id: 341, name: 'Close-Grip Front Lat Pulldown', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 342, name: 'Close-Grip Push-Up off of a Dumbbell', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 343, name: 'Close-Grip Standing Barbell Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 344, name: 'Close-Hands Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 345, name: 'Close-Stance Dumbbell Front Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 346, name: 'Cobra Triceps Extension', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 347, name: 'Cocoons', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 348, name: 'Concentration Curls', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 349, name: 'Crab Toe Touch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 350, name: 'Cross Body Hammer Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 351, name: 'Cross Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 352, name: 'Cross Over - With Bands', muscle_id: 11, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 353, name: 'Cross-Body Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 354, name: 'Crunch - Hands Overhead', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 355, name: 'Crunch - Legs On Exercise Ball', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 356, name: 'Crunches', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 357, name: 'Cuban Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 358, name: 'Dead Bug', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 359, name: 'Decline Barbell Bench Press', muscle_id: 11, exercise_type_id: 5 },
    { id: 360, name: 'Decline Close-Grip Bench To Skull Crusher', exercise_type_id: 5 },
    { id: 361, name: 'Decline Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 362, name: 'Decline Dumbbell Bench Press', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 363, name: 'Decline Dumbbell Flyes', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 364, name: 'Decline Dumbbell Triceps Extension', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 365, name: 'Decline EZ Bar Triceps Extension', exercise_type_id: 5 },
    { id: 366, name: 'Decline Oblique Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 367, name: 'Decline Push-Up', muscle_id: 11, equipment_type_id: 10, exercise_type_id: 5 },
    { id: 368, name: 'Decline Reverse Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 369, name: 'Decline Smith Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 370, name: 'Diamond Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 371, name: 'Dip Machine', equipment_type_id: 6, exercise_type_id: 5 },
    { id: 372, name: 'Dips - Chest Version', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 373, name: 'Dips - Triceps Version', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 374, name: 'Dive Bomber Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 375, name: 'Donkey Calf Raises', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 376, name: 'Double Kettlebell Alternating Hang Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 377, name: 'Double Kettlebell Jerk', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 378, name: 'Double Kettlebell Push Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 379, name: 'Double Kettlebell Snatch', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 380, name: 'Double Kettlebell Windmill', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 381, name: 'Downward Facing Balance', muscle_id: 15, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 382, name: 'Drag Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 383, name: 'Dumbbell Alternate Bicep Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 384, name: 'Dumbbell Alternating Lunge', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 385, name: 'Dumbbell Bench Press', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 386, name: 'Dumbbell Bench Press with Neutral Grip', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 387, name: 'Dumbbell Bicep Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 388, name: 'Dumbbell Clean', muscle_id: 17, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 389, name: 'Dumbbell Clean And Jerk', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 390, name: 'Dumbbell Flyes', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 391, name: 'Dumbbell Front Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 392, name: 'Dumbbell Goblet Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 393, name: 'Dumbbell Incline Row', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 394, name: 'Dumbbell Incline Shoulder Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 395, name: 'Dumbbell Lunge and Curl', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 396, name: 'Dumbbell Lunges', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 397, name: 'Dumbbell Lying One-Arm Rear Lateral Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 398, name: 'Dumbbell Lying Pronation', muscle_id: 13, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 399, name: 'Dumbbell Lying Rear Lateral Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 400, name: 'Dumbbell Lying Supination', muscle_id: 13, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 401, name: 'Dumbbell One-Arm Shoulder Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 402, name: 'Dumbbell One-Arm Triceps Extension', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 403, name: 'Dumbbell One-Arm Upright Row', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 404, name: 'Dumbbell Overhead Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 405, name: 'Dumbbell Pistol Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 406, name: 'Dumbbell Prone Incline Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 407, name: 'Dumbbell Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 408, name: 'Dumbbell Rear Delt Row', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 409, name: 'Dumbbell Rear Lunge', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 410, name: 'Dumbbell Scaption', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 411, name: 'Dumbbell Seated One-Leg Calf Raise', muscle_id: 9, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 412, name: 'Dumbbell Shoulder Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 413, name: 'Dumbbell Shrug', muscle_id: 14, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 414, name: 'Dumbbell Side Bend', muscle_id: 1, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 415, name: 'Dumbbell Squat', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 416, name: 'Dumbbell Squat Snatch', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 417, name: 'Dumbbell Squat To A Bench', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 418, name: 'Dumbbell Squat To Shoulder Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 419, name: 'Dumbbell Step Ups', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 420, name: 'Dumbbell Tricep Extension -Pronated Grip', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 421, name: 'Dumbbell V-Sit Cross Jab', muscle_id: 1, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 422, name: 'Dumbbell Walking Lunge', muscle_id: 10, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 423, name: 'Elbow to Knee', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 424, name: 'Elevated Back Lunge', muscle_id: 10, exercise_type_id: 5 },
    { id: 425, name: 'Elevated Cable Rows', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 426, name: 'Exercise Ball Crunch', muscle_id: 1, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 427, name: 'Exercise Ball Pull-In', muscle_id: 1, equipment_type_id: 13, exercise_type_id: 5 },
    { id: 428, name: 'Extended Range One-Arm Kettlebell Floor Press', muscle_id: 11, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 429, name: 'External Rotation', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 430, name: 'External Rotation with Band', muscle_id: 12, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 431, name: 'External Rotation with Cable', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 432, name: 'EZ-Bar Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 433, name: 'EZ-Bar Skullcrusher', exercise_type_id: 5 },
    { id: 434, name: 'Face Pull', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 435, name: 'Feet-Elevated TRX Push-Up', muscle_id: 11, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 436, name: 'Finger Curls', muscle_id: 13, exercise_type_id: 5 },
    { id: 437, name: 'Fire Hydrant', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 438, name: 'Flat Bench Cable Flyes', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 439, name: 'Flat Bench Leg Pull-In', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 440, name: 'Flat Bench Lying Leg Raise', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 441, name: 'Flexor Incline Dumbbell Curls', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 442, name: 'Floor Glute-Ham Raise', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 5 },
    { id: 443, name: 'Flutter Kicks', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 444, name: 'Forward Band Walk', muscle_id: 10, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 445, name: 'Freehand Jump Squat', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 446, name: 'Frog Sit-Ups', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 447, name: 'Front Barbell Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 448, name: 'Front Barbell Squat To A Bench', muscle_id: 10, exercise_type_id: 5 },
    { id: 449, name: 'Front Cable Raise', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 450, name: 'Front Dumbbell Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 451, name: 'Front Dumbbell Raise Using Towel', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 452, name: 'Front Incline Dumbbell Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 453, name: 'Front Plate Raise', muscle_id: 12, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 454, name: 'Front Raise And Pullover', muscle_id: 11, exercise_type_id: 5 },
    { id: 455, name: 'Front Squat (Bodybuilder)', muscle_id: 10, exercise_type_id: 5 },
    { id: 456, name: 'Front Squat (Clean Grip)', muscle_id: 10, exercise_type_id: 5 },
    { id: 457, name: 'Front Squat Push Press', muscle_id: 10, exercise_type_id: 5 },
    { id: 458, name: 'Front Squats With Two Kettlebells', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 459, name: 'Front Two-Dumbbell Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 460, name: 'Front-To-Back Squat With Belt', muscle_id: 10, exercise_type_id: 5 },
    { id: 461, name: 'Full Moon', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 462, name: 'Full Range-Of-Motion Lat Pulldown', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 463, name: 'Gironda Sternum Chins', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 464, name: 'Glute Bridge Hamstring Walkout', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 465, name: 'Glute Kickback', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 466, name: 'Goblet Squat', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 467, name: 'Gorilla Chin/Crunch', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 468, name: 'Hack Squat', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 469, name: 'Half-kneeling Dumbbell Shoulder Press', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 470, name: 'Hammer Curls', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 471, name: 'Hammer Grip Incline DB Bench Press', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 472, name: 'Hammer Plate Curl', muscle_id: 7, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 473, name: 'Hand Release Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 474, name: 'Hand Stand Push-Up', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 475, name: 'Handstand Push-Ups', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 476, name: 'Hanging Leg Raise', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 477, name: 'Hanging Oblique Knee Raise', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 478, name: 'Hanging Pike', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 479, name: 'High Cable Curls', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 480, name: 'Hip Extension with Bands', muscle_id: 15, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 481, name: 'Hip Flexion with Band', muscle_id: 10, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 482, name: 'Hyperextensions (Back Extensions)', muscle_id: 4, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 483, name: 'Hyperextensions With No Hyperextension Bench', muscle_id: 4, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 484, name: 'Incline Barbell Triceps Extension', exercise_type_id: 5 },
    { id: 485, name: 'Incline Bench Pull', muscle_id: 6, exercise_type_id: 5 },
    { id: 486, name: 'Incline Cable Chest Press', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 487, name: 'Incline Cable Flye', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 488, name: 'Incline Dumbbell Bench With Palms Facing In', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 489, name: 'Incline Dumbbell Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 490, name: 'Incline Dumbbell Flyes', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 491, name: 'Incline Dumbbell Flyes - With A Twist', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 492, name: 'Incline Dumbbell Press', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 493, name: 'Incline Dumbbell Press Reverse-Grip', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 494, name: 'Incline Hammer Curls', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 495, name: 'Incline Inner Biceps Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 496, name: 'Incline Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 497, name: 'Incline Push-Up Close-Grip', equipment_type_id: 5, exercise_type_id: 5 },
    { id: 498, name: 'Incline Push-Up Medium', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 499, name: 'Incline Push-Up Reverse Grip', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 500, name: 'Incline Push-Up Wide', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 501, name: 'Internal Rotation with Band', muscle_id: 12, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 502, name: 'Inverted Row', muscle_id: 6, equipment_type_id: 10, exercise_type_id: 5 },
    { id: 503, name: 'Inverted Row with Straps', muscle_id: 6, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 504, name: 'Iron Cross', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 505, name: 'Isometric Neck Exercise - Front And Back', muscle_id: 8, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 506, name: 'Isometric Neck Exercise - Sides', muscle_id: 8, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 507, name: 'Isometric Wipers', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 508, name: 'Jackknife Sit-Up', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 509, name: 'Janda Sit-Up', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 510, name: 'Jefferson Squats', muscle_id: 10, exercise_type_id: 5 },
    { id: 511, name: 'JM Press', exercise_type_id: 5 },
    { id: 512, name: 'JM Press', exercise_type_id: 5 },
    { id: 513, name: 'JM Press With Bands', exercise_type_id: 5 },
    { id: 514, name: 'Kettlebell 3-Point Extension', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 515, name: 'Kettlebell Arnold Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 516, name: 'Kettlebell Curtsy Lunge', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 517, name: 'Kettlebell Dead Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 518, name: 'Kettlebell Figure 8', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 519, name: 'Kettlebell Hang Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 520, name: 'Kettlebell One-Legged Deadlift', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 521, name: 'Kettlebell Pass Between The Legs', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 522, name: 'Kettlebell Pirate Ships', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 523, name: 'Kettlebell Pistol Squat', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 524, name: 'Kettlebell Seated Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 525, name: 'Kettlebell Seesaw Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 526, name: 'Kettlebell Side Squat', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 527, name: 'Kettlebell Squat Clean', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 528, name: 'Kettlebell Sumo High Pull', muscle_id: 14, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 529, name: 'Kettlebell Sumo Squat', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 530, name: 'Kettlebell Thruster', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 531, name: 'Kettlebell Thruster Progression', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 532, name: 'Kettlebell Turkish Get-Up (Lunge style)', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 533, name: 'Kettlebell Turkish Get-Up (Squat style)', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 534, name: 'Kettlebell Windmill', muscle_id: 1, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 535, name: 'Kipping Muscle Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 536, name: 'Knee/Hip Raise On Parallel Bars', muscle_id: 1, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 537, name: 'Kneeling Cable Crunch With Alternating Oblique Twists', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 538, name: 'Kneeling Cable Triceps Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 539, name: 'Kneeling High Pulley Row', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 540, name: 'Kneeling Single-Arm High Pulley Row', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 541, name: 'L-Sit Chin-Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 542, name: 'Landmine 180\'s', muscle_id: 1, exercise_type_id: 5 },
    { id: 543, name: 'Landmine Linear Jammer', muscle_id: 12, exercise_type_id: 5 },
    { id: 544, name: 'Lateral Band Walk', muscle_id: 3, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 545, name: 'Lateral Raise - With Bands', muscle_id: 12, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 546, name: 'Leg Extensions', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 547, name: 'Leg Lift', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 548, name: 'Leg Press', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 549, name: 'Leg Pull-In', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 550, name: 'Leg-Over Floor Press', muscle_id: 11, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 551, name: 'Leverage Chest Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 552, name: 'Leverage Deadlift', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 553, name: 'Leverage Decline Chest Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 554, name: 'Leverage High Row', muscle_id: 6, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 555, name: 'Leverage Incline Chest Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 556, name: 'Leverage Iso Row', muscle_id: 2, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 557, name: 'Leverage Shoulder Press', muscle_id: 12, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 558, name: 'Leverage Shrug', muscle_id: 14, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 559, name: 'London Bridges', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 560, name: 'Low Cable Crossover', muscle_id: 11, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 561, name: 'Low Cable Triceps Extension', equipment_type_id: 7, exercise_type_id: 5 },
    { id: 562, name: 'Low Pulley Row To Neck', muscle_id: 12, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 563, name: 'Lunge Pass Through', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 564, name: 'Lunge Sprint', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 565, name: 'Lying Cable Curl', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 566, name: 'Lying Cambered Barbell Row', muscle_id: 6, exercise_type_id: 5 },
    { id: 567, name: 'Lying Close-Grip Bar Curl On High Pulley', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 568, name: 'Lying Close-Grip Barbell Triceps Extension Behind The Head', exercise_type_id: 5 },
    { id: 569, name: 'Lying Close-Grip Barbell Triceps Press To Chin', exercise_type_id: 5 },
    { id: 570, name: 'Lying Dumbbell Tricep Extension', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 571, name: 'Lying Face Down Plate Neck Resistance', muscle_id: 8, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 572, name: 'Lying Face Up Plate Neck Resistance', muscle_id: 8, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 573, name: 'Lying High Bench Barbell Curl', muscle_id: 7, exercise_type_id: 5 },
    { id: 574, name: 'Lying Leg Curls', muscle_id: 17, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 575, name: 'Lying Machine Squat', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 576, name: 'Lying One-Arm Lateral Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 577, name: 'Lying Rear Delt Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 578, name: 'Lying Supine Dumbbell Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 579, name: 'Lying T-Bar Row', muscle_id: 6, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 580, name: 'Lying Triceps Press', exercise_type_id: 5 },
    { id: 581, name: 'Machine Bench Press', muscle_id: 11, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 582, name: 'Machine Bicep Curl', muscle_id: 7, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 583, name: 'Machine Lateral Raise', muscle_id: 12, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 584, name: 'Machine Preacher Curls', muscle_id: 7, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 585, name: 'Machine Shoulder (Military) Press', muscle_id: 12, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 586, name: 'Machine Squat', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 587, name: 'Machine Triceps Extension', equipment_type_id: 6, exercise_type_id: 5 },
    { id: 588, name: 'Machine-Assisted Pull-Up', muscle_id: 2, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 589, name: 'Man Maker', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 590, name: 'Medicine Ball Rotational Throw', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 5 },
    { id: 591, name: 'Medicine-Ball Push-Up', muscle_id: 11, equipment_type_id: 8, exercise_type_id: 5 },
    { id: 592, name: 'Middle Back Shrug', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 593, name: 'Mixed Grip Chin', muscle_id: 6, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 594, name: 'Monster Walk', muscle_id: 3, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 595, name: 'Muscle Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 596, name: 'Narrow Stance Hack Squats', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 597, name: 'Narrow Stance Leg Press', muscle_id: 10, equipment_type_id: 6, exercise_type_id: 5 },
    { id: 598, name: 'Narrow Stance Squats', muscle_id: 10, exercise_type_id: 5 },
    { id: 599, name: 'Natural Glute Ham Raise', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 600, name: 'Neck Bridge Prone', muscle_id: 8, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 601, name: 'Neck Bridge Supine', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 602, name: 'Neck Press', muscle_id: 11, exercise_type_id: 5 },
    { id: 603, name: 'Negative Pull-Up', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 604, name: 'Neutral-Grip Pull Ups', muscle_id: 2, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 605, name: 'Oblique Cable Crunch', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 606, name: 'Oblique Crunches', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 607, name: 'Oblique Crunches - On The Floor', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 608, name: 'One Arm Chin-Up', muscle_id: 6, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 609, name: 'One Arm Dumbbell Bench Press', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 610, name: 'One Arm Dumbbell Preacher Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 611, name: 'One Arm Floor Press', exercise_type_id: 5 },
    { id: 612, name: 'One Arm Lat Pulldown', muscle_id: 2, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 613, name: 'One Arm Pronated Dumbbell Triceps Extension', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 614, name: 'One Arm Supinated Dumbbell Triceps Extension', equipment_type_id: 9, exercise_type_id: 5 },
    { id: 615, name: 'One Leg Barbell Squat', muscle_id: 10, exercise_type_id: 5 },
    { id: 616, name: 'One-Arm Dumbbell Row', muscle_id: 6, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 617, name: 'One-Arm Flat Bench Dumbbell Flye', muscle_id: 11, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 618, name: 'One-Arm High-Pulley Cable Side Bends', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 619, name: 'One-Arm Incline Lateral Raise', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 620, name: 'One-Arm Kettlebell Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 621, name: 'One-Arm Kettlebell Clean and Jerk', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 622, name: 'One-Arm Kettlebell Floor Press', muscle_id: 11, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 623, name: 'One-Arm Kettlebell Jerk', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 624, name: 'One-Arm Kettlebell Military Press To The Side', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 625, name: 'One-Arm Kettlebell Para Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 626, name: 'One-Arm Kettlebell Push Press', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 627, name: 'One-Arm Kettlebell Row', muscle_id: 6, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 628, name: 'One-Arm Kettlebell Snatch', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 629, name: 'One-Arm Kettlebell Split Jerk', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 630, name: 'One-Arm Kettlebell Split Snatch', muscle_id: 12, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 631, name: 'One-Arm Kettlebell Swings', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 632, name: 'One-Arm Long Bar Row', muscle_id: 6, exercise_type_id: 5 },
    { id: 633, name: 'One-Arm Medicine Ball Slam', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 5 },
    { id: 634, name: 'One-Arm Open Palm Kettlebell Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 635, name: 'One-Arm Overhead Kettlebell Squats', muscle_id: 10, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 636, name: 'One-Arm Plank Dumbbell Biceps Curl', muscle_id: 7, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 637, name: 'One-Arm Push-Up', muscle_id: 11, equipment_type_id: 5, exercise_type_id: 5 },
    { id: 638, name: 'One-Arm Side Deadlift', muscle_id: 10, exercise_type_id: 5 },
    { id: 639, name: 'One-Arm Side Laterals', muscle_id: 12, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 640, name: 'One-Legged Cable Kickback', muscle_id: 15, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 641, name: 'Open Palm Kettlebell Clean', muscle_id: 17, equipment_type_id: 4, exercise_type_id: 5 },
    { id: 642, name: 'Otis-Up', muscle_id: 1, equipment_type_id: 12, exercise_type_id: 5 },
    { id: 643, name: 'Overhead Cable Curl', muscle_id: 7, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 644, name: 'Pallof Press', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 645, name: 'Pallof Press With Rotation', muscle_id: 1, equipment_type_id: 7, exercise_type_id: 5 },
    { id: 646, name: 'Palms-Down Dumbbell Wrist Curl Over A Bench', muscle_id: 13, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 647, name: 'Palms-Down Wrist Curl Over A Bench', muscle_id: 13, exercise_type_id: 5 },
    { id: 648, name: 'Palms-Up Barbell Wrist Curl Over A Bench', muscle_id: 13, exercise_type_id: 5 },
    { id: 649, name: 'Palms-Up Dumbbell Wrist Curl Over A Bench', muscle_id: 13, equipment_type_id: 9, exercise_type_id: 5 },
    { id: 650, name: 'Parallel Bar Dip', equipment_type_id: 12, exercise_type_id: 5 },
    { id: 651, name: 'Partner 3-Touch Motion Russian Twist', muscle_id: 1, equipment_type_id: 8, exercise_type_id: 5 },
    { id: 652, name: 'Partner Facing Feet-Elevated Side Plank With Band Row', muscle_id: 6, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 653, name: 'Partner Facing Plank With Band Row', muscle_id: 6, equipment_type_id: 1, exercise_type_id: 5 },
    { id: 654, name: '90/90 Hamstring', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 655, name: 'Adductor', muscle_id: 5, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 656, name: 'Adductor/Groin', muscle_id: 5, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 657, name: 'All Fours Quad Stretch', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 658, name: 'Alternating Leg Swing', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 659, name: 'Ankle Circles', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 660, name: 'Ankle On The Knee', muscle_id: 15, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 661, name: 'Anterior Tibialis-SMR', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 662, name: 'Arm Circles', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 663, name: 'Behind Head Chest Stretch', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 664, name: 'Brachialis-SMR', muscle_id: 7, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 665, name: 'Calf Stretch Elbows Against Wall', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 666, name: 'Calf Stretch Hands Against Wall', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 667, name: 'Calves-SMR', muscle_id: 9, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 668, name: 'Cat Stretch', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 669, name: 'Chair Leg Extended Stretch', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 670, name: 'Chair Lower Back Stretch', muscle_id: 2, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 671, name: 'Chair Upper Body Stretch', muscle_id: 12, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 672, name: 'Chest And Front Of Shoulder Stretch', muscle_id: 11, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 673, name: 'Chest Stretch on Stability Ball', muscle_id: 11, equipment_type_id: 13, exercise_type_id: 6 },
    { id: 674, name: 'Child\'s Pose', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 675, name: 'Chin To Chest Stretch', muscle_id: 8, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 676, name: 'Crossover Reverse Lunge', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 677, name: 'Dancer\'s Stretch', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 678, name: 'Dynamic Back Stretch', muscle_id: 2, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 679, name: 'Dynamic Chest Stretch', muscle_id: 11, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 680, name: 'Elbow Circles', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 681, name: 'Elbows Back', muscle_id: 11, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 682, name: 'Foot-SMR', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 683, name: 'Frog Hops', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 684, name: 'Front Leg Raises', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 685, name: 'Groin and Back Stretch', muscle_id: 5, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 686, name: 'Groiners', muscle_id: 5, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 687, name: 'Hamstring Stretch', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 688, name: 'Hamstring-SMR', muscle_id: 17, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 689, name: 'High Kick', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 690, name: 'Hip Circle', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 691, name: 'Hip Circles (prone)', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 692, name: 'Hip Stretch With Twist', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 693, name: 'Hug A Ball', muscle_id: 4, equipment_type_id: 13, exercise_type_id: 6 },
    { id: 694, name: 'Hug Knees To Chest', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 695, name: 'Iliotibial Tract-SMR', muscle_id: 3, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 696, name: 'Inchworm', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 697, name: 'Intermediate Groin Stretch', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 698, name: 'Intermediate Hip Flexor and Quad Stretch', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 699, name: 'Iron Crosses (stretch)', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 700, name: 'IT Band and Glute Stretch', muscle_id: 3, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 701, name: 'Knee Across The Body', muscle_id: 15, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 702, name: 'Knee Circles', muscle_id: 9, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 703, name: 'Knee To Chest', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 704, name: 'Kneeling Forearm Stretch', muscle_id: 13, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 705, name: 'Kneeling Hip Flexor', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 706, name: 'Latissimus Dorsi-SMR', muscle_id: 2, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 707, name: 'Leg-Up Hamstring Stretch', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 708, name: 'Looking At Ceiling', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 709, name: 'Lower Back Curl', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 710, name: 'Lower Back-SMR', muscle_id: 4, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 711, name: 'Lying Bent Leg Groin', muscle_id: 5, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 712, name: 'Lying Crossover', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 713, name: 'Lying Glute', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 714, name: 'Lying Hamstring', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 715, name: 'Lying Prone Quadriceps', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 716, name: 'Middle Back Stretch', muscle_id: 6, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 717, name: 'Neck-SMR', muscle_id: 8, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 718, name: 'On Your Side Quad Stretch', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 719, name: 'On-Your-Back Quad Stretch', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 720, name: 'One Arm Against Wall', muscle_id: 2, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 721, name: 'One Half Locust', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 722, name: 'One Handed Hang', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 723, name: 'One Knee To Chest', muscle_id: 15, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 724, name: 'Overhead Lat', muscle_id: 2, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 725, name: 'Overhead Stretch', muscle_id: 1, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 726, name: 'Overhead Triceps', equipment_type_id: 5, exercise_type_id: 6 },
    { id: 727, name: 'Pelvic Tilt Into Bridge', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 728, name: 'Peroneals Stretch', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 729, name: 'Peroneals-SMR', muscle_id: 9, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 730, name: 'Piriformis-SMR', muscle_id: 15, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 731, name: 'Posterior Tibialis Stretch', muscle_id: 9, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 732, name: 'Pyramid', muscle_id: 4, equipment_type_id: 13, exercise_type_id: 6 },
    { id: 733, name: 'Quad Stretch', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 734, name: 'Quadriceps-SMR', muscle_id: 10, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 735, name: 'Rear Leg Raises', muscle_id: 10, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 736, name: 'Rhomboids-SMR', muscle_id: 6, equipment_type_id: 2, exercise_type_id: 6 },
    { id: 737, name: 'Round The World Shoulder Stretch', muscle_id: 12, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 738, name: 'Runner\'s Stretch', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 739, name: 'Scissor Kick', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 740, name: 'Seated Biceps', muscle_id: 7, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 741, name: 'Seated Calf Stretch', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 742, name: 'Seated Floor Hamstring Stretch', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 743, name: 'Seated Front Deltoid', muscle_id: 12, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 744, name: 'Seated Glute', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 745, name: 'Seated Glute Stretch', muscle_id: 15, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 746, name: 'Seated Hamstring', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 747, name: 'Seated Hamstring and Calf Stretch', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 748, name: 'Seated Overhead Stretch', muscle_id: 1, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 749, name: 'Shoulder Circles', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 750, name: 'Shoulder Raise', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 751, name: 'Shoulder Stretch', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 752, name: 'Side Leg Raises', muscle_id: 5, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 753, name: 'Side Lying Groin Stretch', muscle_id: 5, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 754, name: 'Side Neck Stretch', muscle_id: 8, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 755, name: 'Side Wrist Pull', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 756, name: 'Side-Lying Floor Stretch', muscle_id: 2, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 757, name: 'Single-Leg Balance', muscle_id: 17, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 758, name: 'Sit Squats', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 759, name: 'Spinal Stretch', muscle_id: 6, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 760, name: 'Split Squats', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 761, name: 'Standing Biceps Stretch', muscle_id: 7, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 762, name: 'Standing Elevated Quad Stretch', muscle_id: 10, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 763, name: 'Standing Gastrocnemius Calf Stretch', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 764, name: 'Standing Hamstring and Calf Stretch', muscle_id: 17, equipment_type_id: 12, exercise_type_id: 6 },
    { id: 765, name: 'Standing Hip Circles', muscle_id: 3, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 766, name: 'Standing Hip Flexors', muscle_id: 10, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 767, name: 'Standing Lateral Stretch', muscle_id: 1, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 768, name: 'Standing Pelvic Tilt', muscle_id: 4, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 769, name: 'Standing Soleus And Achilles Stretch', muscle_id: 9, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 770, name: 'Standing Toe Touches', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 771, name: 'Stomach Vacuum', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 772, name: 'Superman', muscle_id: 4, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 773, name: 'The Straddle', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 774, name: 'Toe Touchers', muscle_id: 1, equipment_type_id: 5, exercise_type_id: 6 },
    { id: 775, name: 'Torso Rotation', muscle_id: 1, equipment_type_id: 13, exercise_type_id: 6 },
    { id: 776, name: 'Tricep Side Stretch', equipment_type_id: 10, exercise_type_id: 6 },
    { id: 777, name: 'Triceps Stretch', equipment_type_id: 10, exercise_type_id: 6 },
    { id: 778, name: 'Upper Back Stretch', muscle_id: 6, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 779, name: 'Upper Back-Leg Grab', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 780, name: 'Upward Stretch', muscle_id: 12, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 781, name: 'Windmills', muscle_id: 3, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 782, name: 'World\'s Greatest Stretch', muscle_id: 17, equipment_type_id: 10, exercise_type_id: 6 },
    { id: 783, name: 'Wrist Circles', muscle_id: 13, equipment_type_id: 5, exercise_type_id: 6 }
  ]));
